modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}" #mandatory
license="${mod_license}"
issueTrackerURL="https://github.com/chemiofitor/TETinker/issues"
[[mods]]
modId="tetinker" #mandatory
version="${mod_version}" #mandatory
displayName="Technical Engineering 3 Tinker" #mandatory
logoFile="tetinker.png"
credits="Thanks for this example mod goes to Java"
authors="${mod_authors}"
description='''${mod_description}'''
[[dependencies.tetinker]]
   modId="forge"
   mandatory=true
   versionRange="${forge_version_range}"
   ordering="NONE"
   side="BOTH"
[[dependencies.tetinker]]
   modId="minecraft"
   mandatory=true
   versionRange="${minecraft_version_range}"
   ordering="NONE"
   side="BOTH"
[[dependencies.tetinker]]
   modId="ten3"
   mandatory=true
   versionRange="[18.0,)"
   ordering="NONE"
   side="BOTH"
[[dependencies.tetinker]]
   modId="tconstruct"
   mandatory=true
   versionRange="[3.6.4,)"
   ordering="NONE"
   side="BOTH"
